### ISSUE TITLE
Docker build on M1 Mac can fail if the buildkit output includes timings/timestamps

### ISSUE THREAD

**Issue by olhado** [test-kitchen/kitchen-docker#389] opened 2022-03-14 18:46 UTC
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Running `kitchen create` for a platform throws a `Could not parse Docker build output for image ID` error when building ubuntu 20.04 images.

## Version

2.12.0

## Environment

Mac OS 12.2.1; M1 Mac Book Pro.

Running:
* kitchen 2.12.0
* Ruby 2.7.3
* Docker Desktop 4.5.0 (74594)

Also had to set `"deprecatedCgroupv1": true` in my Docker Desktop settings.json due to issues newer Docker Desktop versions have with cgroups and running systemd inside containers..

## Scenario

Trying to create images for testing with systemd running using `kitchen create default-ubuntu-2004` to test the installation and start of a package that installs itself as a service.

## Steps to Reproduce

1. Set up the platform as defined in [bad-platform.txt](https://github.com/test-kitchen/kitchen-docker/files/8247749/bad-platform.txt)
2. Run `kitchen create default-ubuntu-2004`

## Expected Result

A working, running test image should be created without error.

## Actual Result

Here is the last output:
```
       #23 exporting to image
       #23 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
       #23 exporting layers
       #23 exporting layers 4.7s done
       #23 writing image sha256:e01ff99288c70d4db50f72ea58bc399bcbc1988dfd20bd7493ee680ce4f16075 0.0s done
       #23 DONE 4.7s
```

Error from log is:
```
I, [2022-03-14T14:37:42.408169 #91169]  INFO -- default-ubuntu-2004: -----> Creating <default-ubuntu-2004>...
E, [2022-03-14T14:37:45.188474 #91169] ERROR -- default-ubuntu-2004: Create failed on instance <default-ubuntu-2004>.
E, [2022-03-14T14:37:45.190256 #91169] ERROR -- default-ubuntu-2004: ------Exception-------
E, [2022-03-14T14:37:45.208686 #91169] ERROR -- default-ubuntu-2004: Class: Kitchen::ActionFailed
E, [2022-03-14T14:37:45.227031 #91169] ERROR -- default-ubuntu-2004: Message: Could not parse Docker build output for image ID
E, [2022-03-14T14:37:45.228005 #91169] ERROR -- default-ubuntu-2004: ----------------------
E, [2022-03-14T14:37:45.228095 #91169] ERROR -- default-ubuntu-2004: ------Backtrace-------
E, [2022-03-14T14:37:45.228125 #91169] ERROR -- default-ubuntu-2004: $RUBY_HOME/lib/ruby/gems/2.7.0/gems/kitchen-docker-2.12.0/lib/kitchen/docker/helpers/image_helper.rb:38:in `parse_image_id'
E, [2022-03-14T14:37:45.228157 #91169] ERROR -- default-ubuntu-2004: $RUBY_HOME/lib/ruby/gems/2.7.0/gems/kitchen-docker-2.12.0/lib/kitchen/docker/helpers/image_helper.rb:67:in `build_image'
E, [2022-03-14T14:37:45.228251 #91169] ERROR -- default-ubuntu-2004: $RUBY_HOME/lib/ruby/gems/2.7.0/gems/kitchen-docker-2.12.0/lib/kitchen/docker/container/linux.rb:41:in `create'
E, [2022-03-14T14:37:45.228278 #91169] ERROR -- default-ubuntu-2004: $RUBY_HOME/lib/ruby/gems/2.7.0/gems/kitchen-docker-2.12.0/lib/kitchen/driver/docker.rb:124:in `create'
```

## :heavy_plus_sign: Additional context

Running this with `DOCKER_BUILDKIT=0` works, but then kitchen docker ignores trying to cross build to the amd64 architecture.

This issue appears to be related to one of the changes in #382 or #386

**Comment by olhado** [comment] 2022-03-14 20:08
It looks like the issue is at https://github.com/test-kitchen/kitchen-docker/blob/main/lib/kitchen/docker/helpers/image_helper.rb#L29-L30. The docker output includes timing info of the operation, which breaks the regex here.

**Comment by RulerOf** [comment] 2022-03-14 20:35
@olhado I was about to say that I was unable to reproduce the issue, then I updated Docker Desktop and went from 4.4.2 -> 4.6.0 and still can't reproduce it. Regardless, you're absolutely right about the cause here. Is it possible for you to update Docker Desktop to confirm that this only happens on 4.5.0?

**Comment by olhado** [comment] 2022-03-14 21:09
Upgrading did fix it! Ubuntu 20.04 images on arm and amd created without error.

**Comment by olhado** [comment] 2022-03-16 14:46
@RulerOf Should I close this, or do you want it open as a reminder to add some documentation?

**Comment by RulerOf** [comment] 2022-03-16 17:24
@olhado I decided to submit a PR since I think it's safe to expand the regex for this, even if I can't find the code that explains exactly how this feature works. If possible, I'd ask that you change the issue title to something like "Docker build fails when buildkit output includes timing info"

Then we can leave it to the merge action to close the issue.

**Comment by olhado** [comment] 2022-03-16 17:47
This work?

**Comment by RulerOf** [comment] 2022-03-22 21:49
@olhado I've finally reproduced this. It only happens when I have an existing container that I destroy then immediately recreate, such as:

```shell
kitchen converge; kitchen test
```

**Comment by olhado** [comment] 2022-03-28 14:39
That makes sense, as I was doing a lot of `kitchen create/verify` and `kitchen destroy`. Doing a `docker system prune -f` avoids the issue, but is a bit annoying as it can add a bit of time to the tests recreating the docker image.

**Closed** 2022-04-03 16:06 UTC
